### ISSUE TITLE
Missing React dependency?

### ISSUE THREAD

**Issue by grigio** [thereactivestack/meteor-react-router#1]
I tried to install `react-router-ssr` again but I get this error
```
W20150807-10:27:15.715(2)? (STDERR) /Users/grigio/.meteor/packages/meteor-tool/.1.1.4.ygiyde++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20150807-10:27:15.715(2)? (STDERR) 						throw(ex);
W20150807-10:27:15.715(2)? (STDERR) 						      ^
W20150807-10:27:15.771(2)? (STDERR) TypeError: Cannot read property 'PropTypes' of undefined
W20150807-10:27:15.771(2)? (STDERR)     at Object.<anonymous> (packages/node_modules/react-router/lib/PropTypes.js:17:1)
W20150807-10:27:15.771(2)? (STDERR)     at Object../History (packages/node_modules/react-router/lib/PropTypes.js:44:1)
W20150807-10:27:15.771(2)? (STDERR)     at s (packages/../../../../../../home/benoit/.meteor/packages/cosmos_browserify/.0.5.0.ntol2u++os+web.browser+web.cordova/plugin.CosmosBrowserify.os/npm/CosmosBrowserify/node_modules/browserify/node_modules/browser-pack/_prelude.js:1:1)
W20150807-10:27:15.771(2)? (STDERR)     at packages/../../../../../../home/benoit/.meteor/packages/cosmos_browserify/.0.5.0.ntol2u++os+web.browser+web.cordova/plugin.CosmosBrowserify.os/npm/CosmosBrowserify/node_modules/browserify/node_modules/browser-pack/_prelude.js:1:1
```

**Comment by eXon** [comment]
I'm not sure if this fix the problem, but let me know it it doesn't

**Comment by eXon** [comment]
It seems since the React package has been updated it doesn't work.

**Comment by grigio** [comment]
yes, i still confirm this.
Did you see `packages/../../../../../../home/benoit` have you hardcoded the path somewhere?

**Comment by eXon** [comment]
Their is no hard-coded path. It is probably because of the .map generated on my computer.

**Comment by eXon** [comment]
This should be fixed. I had the same issue and it had to do with React being not anymore in the global scope. Weird.
