### ISSUE TITLE
Error after 0.1.6 update

### ISSUE THREAD

**Issue by ryanfields** [thereactivestack/meteor-react-router#2]
Just updated my packages via ```meteor update``` and am suddenly getting the following:

```
W20150909-16:13:32.978(-4)? (STDERR) error while server-rendering ReferenceError: Map is not defined
W20150909-16:13:32.979(-4)? (STDERR)     at packages/../../../../../../thereactivestack/meteor-react-router/.npm/package/node_modules/react-router/lib/useRoutes.js:74:1
W20150909-16:13:32.979(-4)? (STDERR)     at [object Object].componentWillMount (packages/../../../../../../thereactivestack/meteor-react-router/.npm/package/node_modules/react-router/lib/Router.js:84:1)
W20150909-16:13:32.979(-4)? (STDERR)     at [object Object].ReactCompositeComponentMixin.mountComponent (packages/node_modules/react/lib/ReactCompositeComponent.js:228:1)
W20150909-16:13:32.979(-4)? (STDERR)     at [object Object].wrapper [as mountComponent] (packages/node_modules/react/lib/ReactPerf.js:70:1)
W20150909-16:13:32.979(-4)? (STDERR)     at packages/node_modules/react/lib/ReactServerRendering.js:42:1
W20150909-16:13:32.980(-4)? (STDERR)     at ReactServerRenderingTransaction.Mixin.perform (packages/node_modules/react/lib/Transaction.js:134:1)
W20150909-16:13:32.980(-4)? (STDERR)     at Object.renderToString (packages/node_modules/react/lib/ReactServerRendering.js:39:1)
W20150909-16:13:32.980(-4)? (STDERR)     at packages/reactrouter:react-router-ssr/lib/server.jsx:69:24
W20150909-16:13:32.980(-4)? (STDERR)     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
W20150909-16:13:32.980(-4)? (STDERR)     at packages/reactrouter:react-router-ssr/lib/server.jsx:64:30
```

Version updates:

```
react                         upgraded from 0.1.7 to 0.1.10
react-meteor-data             upgraded from 0.1.5 to 0.1.6
react-runtime                 upgraded from 0.13.3_4 to 0.13.3_6
react-runtime-dev             upgraded from 0.13.3_3 to 0.13.3_5
react-runtime-prod            upgraded from 0.13.3_2 to 0.13.3_4
reactrouter:react-router      upgraded from 0.1.4 to 0.1.6
reactrouter:react-router-ssr  upgraded from 0.1.6 to 0.1.8
```

Might be related to https://github.com/rackt/react-router/issues/1793

**Comment by RonaldV** [comment]
I've got the exact same error.

**Comment by eXon** [comment]
This is probably because you don't have the ecmascript package. If you had it, does it fix the problem? (if it does I will add the dependency).

`meteor add ecmascript`

**Comment by eXon** [comment]
FYI it seems like they removed the `new Map()` (which cause the ecmascript dependency) after the beta4 on the master branch but their is no new release yet. Hopefully we will not need to depend on it on the future (even though I personally don't care).

**Comment by eXon** [comment]
This should be fixed
